### ISSUE TITLE
Jumps back and forth between "app" and "storage" windows in EMUI.

### ISSUE THREAD

**Issue by kyoforkshomebrews** [bmx666/android-appcachecleaner#41] opened 2023-01-01 14:39 UTC
I assume the app thinks that the main app page is called something different than emui calls it on my phone, so i think adding the option to also specify the app page string would be a fix.

**Comment by bmx666** [comment] 2023-01-02 18:27
Hi @kyoforkshomebrews , please check issue #6 , [2nd comment](https://github.com/bmx666/android-appcachecleaner/issues/6#issuecomment-1139811053) and post here record or screenshots, it will help a lot to further investigation.

**Comment by kyoforkshomebrews** [comment] 2023-01-03 22:27
Android  10
Huawei P Smart 2019
EMUI 12
Discord
The phone is set to Austrian German (de-at)
Appinfo:
![38236dfe-2ad7-436d-b170-e2de0ae90e32](https://user-images.githubusercontent.com/49304418/210451427-3ce71fee-5efb-4082-ae70-06600c00c8d5.jpg)
storage:
![c30cf2e7-37d7-4ec9-aeb4-327776e28c24](https://user-images.githubusercontent.com/49304418/210451593-393209a5-438a-4f2e-88fe-9663667a8575.jpg)

**Comment by bmx666** [comment] 2023-01-05 21:59
Hi @kyoforkshomebrews

Sorry, but Google doesn't have Austrian German (de-at), only German (de) name for button "Clear cache" as "Cache leeren". Also for Android 8 and later menu should have name "Speicher und Cache", old name from Android 7 and early - "Speicher"

Original resource locale for German can be found here - https://github.com/bmx666/android-appcachecleaner/blob/main/app/src/main/res/values-de/strings.xml

2nd problem - Huawei EMUI use the same name "Speicher" and "Speicher" for 2 different menu! There is no any helpful information from Accessibility View tree, because they are both marked as "**android:id/title**" and contain text "**Speicher**". That's why it's required more complicated logic to identify which menu should be chosen without any helpful background from Accessibility side. The app just get first match and click it. I had this problem with Huawei UI before, and 3rd problem - order of "Storage" and "Storage" is always different on different Android versions and different models...

3rd - to use different name for button "Clear cache" please check [README](https://github.com/bmx666/android-appcachecleaner#customized-settings-ui)

**Comment by kyoforkshomebrews** [comment] 2023-01-07 02:55
I think it opens the right storage menu as far as I can tell? Also I did already enter the custom name for clear cache, that works. But it gets stuck jumping between Storage/ "Speicher" and app info "App-Info".

**Comment by bmx666** [comment] 2023-01-07 04:38
Hi @kyoforkshomebrews 

Can you check debug version? Rename app-debug.zip into app-debug.apk and check 2-3 apps only, it's enough to trace view tree and get elements on screen, otherwise log-file will be huge.

Wait until clean process is completed, save log file somewhere on device and attach it here.

Log file doesn't contain any personal or sensitive information, only app name, app version and Settings view tree. So it's safe to attach here.

[app-debug.zip](https://github.com/bmx666/android-appcachecleaner/files/10365506/app-debug.zip)

**Comment by kyoforkshomebrews** [comment] 2023-01-07 11:01
Ok so here's my log:
[appcachecleaner-log.txt](https://github.com/bmx666/android-appcachecleaner/files/10366055/appcachecleaner-log.txt)

**Comment by bmx666** [comment] 2023-01-07 16:22
Hi @kyoforkshomebrews 

Thanks for the log-file. Really strange, cycled actions, I never faced with this issue before. I will come back later with additional logs.

**Comment by bmx666** [comment] 2023-01-26 18:24
Hi @kyoforkshomebrews 

Sorry for a long delay, I was busy to adapt app for Google Play release. Now it was published and I made for you extra debug version. Can you check it and attach log file?

Rename app-debug.zip into app-debug.apk, install on device and check 2-3 apps only, it's enough to trace

[app-debug.zip](https://github.com/bmx666/android-appcachecleaner/files/10512285/app-debug.zip)

**Comment by kyoforkshomebrews** [comment] 2023-01-26 18:49
Thanks, here is a new log. It seems like it stops after the first app and then nothing happens so then I clicked the big icon on the screen.
[appcachecleaner-log (1).txt](https://github.com/bmx666/android-appcachecleaner/files/10512445/appcachecleaner-log.1.txt)

**Comment by bmx666** [comment] 2023-01-27 16:55
Hi @kyoforkshomebrews 

Strange, according your logs Cache cleaner was stopped manually on 3rd app, because Accessibility Service didn't respond and Cache Cleaner activate timeout trigger for 30s.

Please check conclusion of issue #8 
If this issue is reproducible after reboot, looks like something happens with Accessibility Service inside Android, because Cache cleaner doesn't get feedback from it

**Comment by kyoforkshomebrews** [comment] 2023-01-27 23:14
Ok, now after a reboot it seems to work normally:
[appcachecleaner-log (2).txt](https://github.com/bmx666/android-appcachecleaner/files/10523777/appcachecleaner-log.2.txt)

**Closed** 2023-01-28 02:58 UTC
Labels: question
