### ISSUE TITLE
Problem deleting the cache

### ISSUE THREAD

**Issue by JonatasVi** [bmx666/android-appcachecleaner#6] opened 2022-05-27 00:15 UTC
When the application selects multiple applications to delete the cache, it does not work. It deletes cache but only from some applications and not from all

**Comment by JonatasVi** [comment] 2022-05-31 04:48
Android 11
Motorola G9 Play
Facebook, Tiktok e Instagram
![Screenshot_20220531-004250](https://user-images.githubusercontent.com/86968994/171094624-b670b911-0a62-42af-bf42-63b501c2217e.png)
![Screenshot_20220531-004244](https://user-images.githubusercontent.com/86968994/171094631-82548e80-4bbd-4a6f-b6eb-c3cacecb39c6.png)
![Screenshot_20220531-003546](https://user-images.githubusercontent.com/86968994/171094658-406570c6-bfd4-4223-aa62-405a20a2c4ac.png)
![Screenshot_20220531-004237](https://user-images.githubusercontent.com/86968994/171094662-0c61cdb8-4640-4f37-b97f-8a8047298e64.png)
![Screenshot_20220531-003535](https://user-images.githubusercontent.com/86968994/171094697-428726ae-1629-4d5a-b949-71db59e6b907.png)
![Screenshot_20220531-004224](https://user-images.githubusercontent.com/86968994/171094702-26012387-c85c-4f69-a97c-bb3653896d83.png)

the problem occurs when I select multiple apps

**Comment by heberjeur** [comment] 2022-06-01 01:59
I have the same problem with Samsung A50

**Comment by bmx666** [comment] 2022-06-01 07:29
Hi @JonatasVi  thanks for feedback, I will check later those apps on emulator with **Brazilian Portuguese** language.

**Comment by bmx666** [comment] 2022-06-01 07:37
> I have the same problem with Samsung A50

Hi @heberjeur, can you please answer on these question:

- What version of Android do you have?
- What apps is affected? Are the same that @JonatasVi  mention?
- What language by default?

**Comment by bmx666** [comment] 2022-06-03 22:38
Hi @JonatasVi, I tested on emulator and on few different smartphones. Unfortunately I can't reproduce this issue. Only one thing I noticed - after clear cache some applications restores their cache back. Like Instagram always resets back to 10Mb after clean.

**Comment by JonatasVi** [comment] 2022-06-04 00:29
did you select all?

Em sex., 3 de jun. de 2022 18:38, Maxim Paymushkin ***@***.***>
escreveu:

**Comment by heberjeur** [comment] 2022-06-04 12:03
* Android version
> Android 11 
>     * Smartphone model
> Samsung Galaxy A50, One Ui 3.1,French Language
>     * Has phone custom Settings implementation? Like Xaomi, Huawei and Samsung companies do
> No
>     It would also be nice to know steps you did to reproduce this issue.
It doesn't works for all installed user and system applications
I use the last version you have made 0.0.3
I make screenshot with Android Assistant App that works like your application
Note: I tried to complete clean the cache but your application stopped in the middle, I tried with user cleaner cache (84app), and all cleaner cache (~470app) it was the same result
![Screenshot_20220604-123749_Android Assistant](https://user-images.githubusercontent.com/11852634/171997788-41178b85-a601-4def-8a9a-1db59333b851.jpg)
![Screenshot_20220604-123740_Android Assistant](https://user-images.githubusercontent.com/11852634/171997795-5839b1fb-07c3-4f12-8325-c3bdd9937c15.jpg)
![Screenshot_20220604-123731_Android Assistant](https://user-images.githubusercontent.com/11852634/171997805-ebb416dc-057a-44ec-ae96-6ca3e166b1b6.jpg)
![Screenshot_20220604-123723_Android Assistant](https://user-images.githubusercontent.com/11852634/171997811-dfd4b9ba-b948-4c00-8444-f538feab32b4.jpg)
![Screenshot_20220604-123714_Android Assistant](https://user-images.githubusercontent.com/11852634/171997817-cb632fb6-6ebe-4c6f-95fd-cb16e5162403.jpg)
![Screenshot_20220604-121933_Android Assistant](https://user-images.githubusercontent.com/11852634/171997820-d2827a87-f1a6-4bdb-9b68-337761449337.jpg)
![Screenshot_20220604-121859_Android Assistant](https://user-images.githubusercontent.com/11852634/171997829-fe925fe3-e270-438c-a1bc-8c2148db2663.jpg)
![Screenshot_20220604-121848_Android Assistant](https://user-images.githubusercontent.com/11852634/171997835-2961f040-592f-4a3d-9d27-372888089a25.jpg)
![Screenshot_20220604-121838_Android Assistant](https://user-images.githubusercontent.com/11852634/171997840-f8969cf2-e40c-4dde-8cf3-3ad55ca134ed.jpg)
![Screenshot_20220604-121828_Android Assistant](https://user-images.githubusercontent.com/11852634/171997847-e4257964-cc5f-48d0-96ba-0a0142b992e2.jpg)

**Comment by heberjeur** [comment] 2022-06-04 12:07
For example, those are the screenshots of Handy News
![Screenshot_20220604-123641_Settings](https://user-images.githubusercontent.com/11852634/171998165-a4c33e68-bfb5-4b42-bd2c-70656ea7b8e2.jpg)
![Screenshot_20220604-122110_AppCacheCleaner](https://user-images.githubusercontent.com/11852634/171998168-325dd863-378a-474f-92f2-7ea0dc64e348.jpg)
![Screenshot_20220604-121747_Settings](https://user-images.githubusercontent.com/11852634/171998172-46c33cef-cdb4-42c2-a03d-e5a4fe035f0e.jpg)

**Comment by bmx666** [comment] 2022-06-04 15:17
Hi @heberjeur, thanks for feedback

1. A lot screenshots of "Assistant for Android" is not related to this issue.
2. I tested "Assistant for Android" and it doesn't work correctly on Android 12.
3. According the latest screenshot your Settings App has modified UI, but you answered as "NO" and Settings App doesn't look like original Android Settings App at all. It can cause problem for Accessibility to find UI-widgets like "buttons", "list" and etc. To fix my app for your UI, I should get full dump on UI-widgets to understand what exactly "element" Accessibility should looking for. 2nd problem - translation of UI-widgets can be different from original Android, because it custom Settings App.
4. I don't know what are you expected if you don't even checked "Handy News Reader" app in list (screenshot) ? Algorithm is simple -> check required apps to clean and press float button "Clean cache"

**Comment by bmx666** [comment] 2022-06-04 15:26
Hi @JonatasVi  I tried several options:

1. All users apps
2. Select users apps and check only Facebook, Instagram and TikTok apps
3. All apps
4. Select all apps and check only Facebook, Instagram and TikTok apps

**Comment by heberjeur** [comment] 2022-06-04 18:31
What means "custom Settings implementation?", I have the original Samsung Android configurations, Samsung have their own launcher One Ui, the Settings page like other Android interfaces
![Screenshot_20220604-180309_Settings](https://user-images.githubusercontent.com/11852634/172020723-d9aba224-e8d8-47cd-9996-98fe3fe1f8d8.jpg)

 `I tested "Assistant for Android" and it doesn't work correctly on Android 12.` I have Android 11

`check required apps to clean and press float button "Clean cache"`yes of course I have checked this button.

**Comment by bmx666** [comment] 2022-06-04 18:46
Hi @heberjeur , **Samsung has different UI** then **original UI Android**. Original UI should look like @JonatasVi posted at the beginning.

I also tested on Android 8 and Android 11, same issue with "Assistant for Android" app.

**Comment by heberjeur** [comment] 2022-06-04 19:02
I don't have any issue with Android Assistant just I like your application because it's open source

**Comment by bmx666** [comment] 2022-06-05 14:05
Hi @heberjeur  and @JonatasVi  I have a plan to create Accessibility logger to dump into file in the future, it can trace all steps and behavior or my app to find issues. Otherwise it's hard to solve Accessibility issue without physically access to your smartphones.

**Comment by JonatasVi** [comment] 2022-06-05 14:40
@bmx666 Got it, I don't know why this problem.  but if you managed to put this plan into action maybe with him you can find out the problem

**Comment by bmx666** [comment] 2022-06-05 16:45
Hi @JonatasVi  I found one related issue on slow devices cache is not calculated yet and "Clear cache" button is disabled until calculation of storage will be finished and displayed, then this button goes to state -> "Enabled", but Accessibility UI doesn't get any event about it.

Special "delayed" logic should be implemented to wait until data will be calculated and then button "Clear cache" will be enabled, then I can press it. But I have 5s main timer to kill window and go to the next app, otherwise whole loop can stuck, because system apps doesn't have "Storage" or it not available at all...

**Comment by heberjeur** [comment] 2022-06-05 17:10
> Hi @heberjeur and @JonatasVi I have a plan to create Accessibility logger to dump into file in the future, it can trace all steps and behavior of my app to find issues. Otherwise it's hard to solve Accessibility issue without physically access to your smartphones.

Hi @bmx666,  If that respects our privacy, got it, I suggest to make two versions, beta that contains those tools and stable that represent the official application without loggers.

**Comment by bmx666** [comment] 2022-06-27 01:03
Hi @heberjeur and @JonatasVi I made debug log version.

[app-debug.zip](https://github.com/bmx666/android-appcachecleaner/files/8987886/app-debug.zip)

App generate log txt-file when clean cache will be finished, and it suggests to share it via any Android apps (standard Android file share). I recommend to you select and clean 2-3 apps only, otherwise log will be overloaded with unnecessary information. Log doesn't include private or sensitive information except app name and version. You can attach a log txt-file here. Then I can analyze it and I will try to solve issue.

**Comment by heberjeur** [comment] 2022-06-28 10:15
The debug doesn't work for me, I think you should give your application the storage permission to save contents, I send to you the log file that I received but it's 0 ko !, those s

![Screenshot_20220628-105651_Settings](https://user-images.githubusercontent.com/11852634/176151406-844e7e0d-0ebb-4b0f-a69e-a4d6e8332b8e.jpg)

![Screenshot_20220628-105637_Settings](https://user-images.githubusercontent.com/11852634/176151423-50baae5d-31a5-4460-ac50-72ebfc6279ad.jpg)

[log.txt](https://github.com/bmx666/android-appcachecleaner/files/8999890/log.txt)

![Screenshot_20220628-105247_Settings](https://user-images.githubusercontent.com/11852634/176151438-3ea0bb3f-1f5a-4299-97d9-c17a53f6c836.jpg)
![Screenshot_20220628-105130_Settings](https://user-images.githubusercontent.com/11852634/176151449-39224831-cd15-4e4c-8338-1b7fa86bd66e.jpg)

**Comment by JonatasVi** [comment] 2022-06-29 00:37
@bmx666 
[log.txt](https://github.com/bmx666/android-appcachecleaner/files/9006308/log.txt)

**Comment by heberjeur** [comment] 2022-07-02 10:02
@bmx666
[log(1).txt](https://github.com/bmx666/android-appcachecleaner/files/9032782/log.1.txt)

**Comment by bmx666** [comment] 2022-07-02 12:12
Hi @JonatasVi and @heberjeur according your logs everything should be fine and "Clear cache" button must be clicked. I released new [version 0.0.5](https://github.com/bmx666/android-appcachecleaner/releases/tag/v0.0.5) . I still try to improve and find issues.
If you still have same issue, I will continue to make more debuggable version.

**Comment by heberjeur** [comment] 2022-07-02 13:09
Hi @bmx666, I tried the lastest version, I have the same result, can you make another debuggable version ?

Those are my results before and after
![Screenshot_20220702-140346_Settings](https://user-images.githubusercontent.com/11852634/177002165-582f1bbb-58cf-45de-b24c-3cfe82f3e618.jpg)
![Screenshot_20220702-140156_Settings](https://user-images.githubusercontent.com/11852634/177002169-3c715da1-4d88-4665-9e9e-ce2156f28140.jpg)

**Comment by bmx666** [comment] 2022-07-02 19:56
Hi @heberjeur and @JonatasVi I made new debug version.
I disabled share log file, now app stores log files in **/sdcard/Documents/**
After each run new log file will be generated as **appcachecleaner-log.txt**, so you can remove them after upload here.
I added real click detection and click event logging.

[app-debug.zip](https://github.com/bmx666/android-appcachecleaner/files/9033627/app-debug.zip)

**Comment by heberjeur** [comment] 2022-07-03 09:12
This is for facebook app 
[appcachecleaner-log.txt](https://github.com/bmx666/android-appcachecleaner/files/9034415/appcachecleaner-log.txt)

**Comment by bmx666** [comment] 2022-07-03 10:10
> This is for facebook app [appcachecleaner-log.txt](https://github.com/bmx666/android-appcachecleaner/files/9034415/appcachecleaner-log.txt)

Hi @heberjeur , thanks for log, now I found the issue. It can't find label name, because since Android 10 Google is using "Espace de stockage et cache" and for Android 9 and early it was "Stockage".
I got similar feedback for Russian language, when custom UI is used different translation for labels.

Looks like due to huge variety of translation it's better to make array of possible translations of label.

**Comment by heberjeur** [comment] 2022-07-03 10:41
@bmx666 thanks, I'm ready for any tests you want

**Comment by bmx666** [comment] 2022-07-04 16:58
Hi @heberjeur  can you try release [v0.0.6](https://github.com/bmx666/android-appcachecleaner/releases/tag/v0.0.6) ?
I added button "add extra search text" that can help to solve thousands variations of custom UI.
[See more in README](https://github.com/bmx666/android-appcachecleaner/blob/main/README.md#customized-settings-ui)

**Comment by heberjeur** [comment] 2022-07-04 18:16
Finally It works😃, but it doesn't complete all my list, I have 98 user app, I selected all my list, but it stops at 15,not always at 15

**Comment by JonatasVi** [comment] 2022-07-05 00:46
On my mobile it is also working, I selected several and it worked @bmx666

**Comment by bmx666** [comment] 2022-07-06 21:58
> but it doesn't complete all my list, I have 98 user app, I selected all my list, but it stops at 15,not always at 15

Yes, I saw same issue on low performance smartphone, I got two for test. But there are 3 different type of issues:
1. sometimes Android Accessibility itself breaks and only reboot helps
2. long request to flash memory due to degradation, I checked on few cheap smartphones 3 and 5 years old, they calculates cache size for each app several seconds, even factory reset doesn't help
3. I need to fix and refactor Accessibility service and app communication, because I made PoC for fun and now it's not for product placement 😄 

I will close this issue, and create new for described bug.

**Closed by bmx666** 2022-07-06 21:58 UTC

**Comment by bmx666** [comment] 2022-08-10 20:36
Hi @JonatasVi  and @heberjeur  , I made a new release [v0.1.1](https://github.com/bmx666/android-appcachecleaner/releases/download/v0.1.1/app-release.apk) and I hope you will not have new bugs in this release, only improvements :)

**Comment by heberjeur** [comment] 2022-08-10 23:03
It stopped one time, but I couldn't reproduce that. I selected all the apps, and it was quiet when I analyzed the trucaller

![Screenshot_20220810-232934_AppCacheCleaner](https://user-images.githubusercontent.com/11852634/184037800-bac93fbf-0d79-4b01-b7ef-fd5619561672.jpg)

**Comment by heberjeur** [comment] 2022-08-10 23:18
In this video, there are two other issues. First, I forced the closure of the trucaller to finish the cleaning. Second, the k9 mail doesn't get cleaned !

https://user-images.githubusercontent.com/11852634/184038263-5ee652e1-a760-41b2-af29-c71515079893.mp4

![Screenshot_20220811-001633_Settings](https://user-images.githubusercontent.com/11852634/184039134-1f7f0f8d-cd46-459c-a1d5-10be23a22fd9.jpg)

**Comment by bmx666** [comment] 2022-08-11 07:29
Hi @heberjeur, when you clean all apps sometimes it's interrupted and I described that problems in issue https://github.com/bmx666/android-appcachecleaner/issues/8#issuecomment-1210908943

If you manually open AppInfo and do "Clear cache" for k-9, it will work or size of cache the same? Android show sum of two separated cache places - internal (/data/data/com.my.package/cache) and external (on /sdcard/Android/...). Android never clears the external cache.

**Comment by heberjeur** [comment] 2022-08-11 09:38
Hi @bmx666 the size of k9 cache is the same, I don't have sdcard !, OK I wait your debug version to resolve the second problem

**Comment by bmx666** [comment] 2022-12-17 12:28
> Hi @bmx666 the size of k9 cache is the same, I don't have sdcard !, OK I wait your debug version to resolve the second problem

In early days, when Android was based on NAND flash, most Android smartphones had external SDCard slot. But during tech progress all smartphones are using EMMC flash and SDCard is emulated now (part of space on  EMMC), replacing old separate way /data + /sdcard partitions, allocating everything in one partition on EMMC flash.
