### ISSUE TITLE
partially not working

### ISSUE THREAD

**Issue by GreenMystic** [bmx666/android-appcachecleaner#170] opened 2023-12-24 09:01 UTC
CC it's working but the thing is CC always stop after clearing 45-50 apps

Realme C21Y
A11 RUI 1.0
RMX 2030

![Screenshot_20231224-160005.png](https://github.com/bmx666/android-appcachecleaner/assets/136427398/c04ab1c8-feba-4ec0-ae2e-4aac3de85f4c)

**Comment by bmx666** [comment] 2023-12-24 09:51
Hi @GreenArchiveForever 

Could you please install debug version?
https://github.com/bmx666/android-appcachecleaner/releases/download/v1.9.5/app-debug.apk

Please set English System Language on your phone (easy to debug).
Select all apps and start process.

After that app will generate log file (no sensitive information, just app names and view tree of AppInfo)
You could attach generated file here.

P.S. After cleaning cache of system apps Accessibility service stop to respond and CC doesn't get any feedback that's why CC stops cleaning process.

**Comment by bmx666** [comment] 2024-01-04 16:07
no reply

**Comment by GreenArchiveForever** [comment] 2024-01-10 16:15
> Hi @GreenArchiveForever 
> 
> Could you please install debug version?
> https://github.com/bmx666/android-appcachecleaner/releases/download/v1.9.5/app-debug.apk
> 
> Please set English System Language on your phone (easy to debug).
> Select all apps and start process.
> 
> After that app will generate log file (no sensitive information, just app names and view tree of AppInfo)
> You could attach generated file here.
> 
> P.S. After cleaning cache of system apps Accessibility service stop to respond and CC doesn't get any feedback that's why CC stops cleaning process.

![appcachecleaner-log.txt](https://github.com/bmx666/android-appcachecleaner/files/13890235/appcachecleaner-log.txt)

sometime i need manual add interaction
(ex: manual tapping on storage and cache) to make app temporary continue working on but still it will stop again after few times

**Comment by GreenArchiveForever** [comment] 2024-01-10 16:16
> no reply 

sorry dev i have busy recently 😅

**Comment by bmx666** [comment] 2024-01-10 20:37
Hi @GreenArchiveForever 

According to the attached log files, CacheCleaner sent an event to Android Settings to open the apps "eu.faircode.netguard" (first log file) and "com.android.providers.telephony" (second log file). However, the Accessibility service did not receive any feedback, which might indicate that the apps could not be opened or there was an issue with the Android Accessibility. Nevertheless, the app "eu.faircode.netguard" was processed without any issues in the second log file, and there were no errors reported from CacheCleaner. This suggests that the problem might lie within the Android System. Such occurrences are expected; sometimes, rebooting the smartphone is the only solution to resolve the issue.

Android is not perfect :)

**Comment by bmx666** [comment] 2024-01-10 22:18
Hi @GreenArchiveForever , I released a new version 1.9.7 to add delay between apps, you can check if it reduce interrupts.

**Comment by GreenArchiveForever** [comment] 2024-01-11 00:45
> Hi @GreenArchiveForever , I released a new version 1.9.7 to add delay between apps, you can check if it reduce interrupts.

idk if this kind of black magic or what
i test with similar app (ccleaner) and it's have no interruptions maybe there is workaround for this problem that we don't know yet

yes accessibility services sometime malfunctioning (in setting will say activated, not functioning)
this can resolved by re activate them and app work properly but not with this app even after reboot 

i literally confused 🥴

**Comment by bmx666** [comment] 2024-01-16 23:41
Hi @GreenArchiveForever please check a new version v1.10.0 - if some app interrupts cleaning process you will see a dialog that suggests to add the app into the list of ignored apps.

**Comment by bmx666** [comment] 2024-06-24 19:34
Hi @GreenMystic 
I already reported to Google about this bug, still no feedback #190

**Comment by bmx666** [comment] 2024-07-24 14:31
Hi @GreenMystic 
Google closed the issue and ignored request. Anyway, after new updates of Android 14 and Android 15, I found a root cause of this behavior. Window Manager doesn't properly handle windows stack, even with flags (no history, on top) to avoid deep stacking, Android creates 50+ open windows in stack and Activity Manager kills Cache Cleaner because it opens many windows. To avoid this behavior the only one correct solution - press globally Back key multiple times to return back into main screen of Cache Cleaner app. It will slow down the cache cleaning process but thanks to Google, there is no other options.

I will try to create a fix for that.

**Comment by bmx666** [comment] 2024-08-02 22:52
Hi @GreenMystic 

I uploaded a new release with a huge update of cache cleaning algorithm.
Could you please verify on your side?
Also you can tune "Go back after N apps" in the Settings, to reduce windows overflow stack in Android.

**Comment by bmx666** [comment] 2024-08-03 15:49
Hi @GreenMystic 

Did you set "Go back after 25 apps"?
Also I would recommend set properties not lower than 2 seconds for Accessibility event, wait clean cache button to 1 second, and wait 3 seconds per app.

**Comment by bmx666** [comment] 2024-08-05 19:38
@GreenMystic nothing special, glad it help.
It could be that your phone has a limit on the number of windows per app, and if it reaches that limit, it will trigger the Activity Manager to prevent the creation of new windows and kill Cache Cleaner as a window spammer.

**Closed by bmx666** 2024-08-05 19:38 UTC
Labels: bug
